#!/usr/bin/env python

import os
import sys
from subprocess import check_output, CalledProcessError
import ruamel.yaml
os.environ['HOME']

def get_git_root():
    try:
        base = check_output('git rev-parse --show-toplevel', shell=True)
    except CalledProcessError:
        raise IOError('Current working directory is not a git repository')

    git_root = base.decode('utf-8').strip()
    if git_root == '': git_root = '.'  # git rev-parse fails, then current dir is git_root

    return git_root


def process_yaml(yaml_file, format_yaml):
    with open(yaml_file, 'r') as y:
        yaml_text = y.read()

    yaml_data = ruamel.yaml.round_trip_load(yaml_text)
    yaml_dump = ruamel.yaml.round_trip_dump(yaml_data, indent=2)

    if yaml_text != yaml_dump and yaml_dump != '...\n':  # only format it when not empty
        if format_yaml:
            with open(yaml_file, 'w') as y:
                y.write(yaml_dump)
            print 'Formatted YAML file: ' + yaml_file
            return 0
        else:
            print 'YAML needs to be formatted: ' + yaml_file
            return 1
    else:
        return 0


def main(format_yaml):
    os.chdir(get_git_root())
    ret_value = 0
    for path, _, files in os.walk("."):
        if path.startswith('./.git') or path.startswith('./git-hooks'):
            continue

        for f in files:
            if f.startswith('.') or not f.endswith('.yaml'):
                continue

            yaml_file = os.path.join(path, f)
            ret_value += process_yaml(yaml_file, format_yaml)

    if ret_value:
        return 1
    else:
        return 0


if __name__ == '__main__':
    format_yaml = 1 if sys.argv[1:] and sys.argv[1] == 'format' else 0

    sys.exit(main(format_yaml))
