---
stages:
  - .pre
  - test
  - build
  - stage_trigger

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.6.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml
      - templates/common/trigger.yml

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [ python3.8, python3.9, python3.10, python3.11 ]
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    ES_HOST: elasticsearch
  script:
    - tox -r -e py --colored yes


release:
  variables:
    RELEASE_PY_VERSION: python3.8
  before_script:
    - git fetch --unshallow || true
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
