---
include:
  - project: nci-gdc/gitlab-templates
    ref: 0.7.6
    file:
      - templates/artifacts/python-library.yaml
      - templates/common/trigger.yml

variables:
  LANGUAGE_VERSION: python3.8

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION: [python3.8, python3.9, python3.10, python3.11]
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    ES_HOST: elasticsearch

publish:
  after_script:
    - python -m setuptools_git_versioning > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt

.downstream_repos:
  parallel:
    matrix:
      - TRIGGERED_REPO: 7
        NAME: gdcapi
      - TRIGGERED_REPO: 79
        NAME: esbuild
