---
include:
  - project: nci-gdc/gitlab-templates
    ref: 0.5.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [ python3.8, python3.9, python3.10, python3.11 ]
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    ES_HOST: elasticsearch
  script:
    - pip install tox
    - tox -r -e py
