---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
          - python3.14
  services:
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:${BASE_CONTAINER_VERSION}
      alias: elasticsearch
  variables:
    ES_HOST: elasticsearch
