version: "3.3"
services:
  elasticsearch:
    image: docker.osdc.io/elasticsearch:7.7.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Dhttps.proxyHost=cloud-proxy -Dhttps.proxyPort=3128
    # TODO Build our own ES image with this preinstalled.
    command: bash -c "elasticsearch-plugin install mapper-size && su -c elasticsearch elasticsearch"
    logging:
      driver: none

  app:
    image: quay.io/ncigdc/jenkins-agent:multipython
    environment:
      HTTPS_PROXY: http://cloud-proxy:3128
      HTTP_PROXY: http://cloud-proxy:3128
    volumes:
      - .:/home/jenkins
    command: bash -c "./wait-for-it.sh localhost:9200 -t 120 && pip install tox tox-poetry pipx -q --user && pipx install poetry && pipx inject poetry poetry-dynamic-versioning && tox -r"
    network_mode: "service:elasticsearch"
    depends_on:
      - elasticsearch
