[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77", "wheel", "setuptools_scm[toml]>=7.0", "versionista>=1.1.0"]

[dependency-groups]
dev = ["coverage", "elasticsearch-dsl~=7.0", "pytest", "testcontainers"]

[project]
authors = [
  {name = "NCI GDC", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}
]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: PythonLicense :: OSI Approved :: Apache Software License",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
  "deepdiff",
  "elasticsearch~=7.0",
  "mergedeep",
  "more-itertools",
  "PyYAML",
  "typing-extensions"
]
description = "Stores and serves GDC data models defined in static YAML files."
dynamic = ["version"]
keywords = ["python3", "gdcmodels", "yaml"]
license-files = ["LICENSE"]
name = "gdcmodels"
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
sync = ["click", "gdcdictionary", "gdcdatamodel2"]

[project.scripts]
init_index = "gdcmodels.init_index:main"
sync-models = "gdcmodels.sync.cli:cli"

[project.urls]
Repository = "https://github.com/NCI-GDC/gdc-models"

[tool.black]
include = '\.pyi?$'
line-length = 95

[tool.coverage.html]
directory = "docs/htmlcov"
show_contexts = true
title = "gdc-models coverage report"

[tool.coverage.run]
branch = true
context = "unit tests"
source = ["gdcmodels"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py310"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  "W" # pydocstyle warnings
]

[tool.ruff.lint.isort]
known-first-party = ["gdcmodels"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"

[tool.tox]
env_list = ["python3.10", "python3.11", "python3.12", "python3.13", "python3.14"]
skip_missing_interpreters = true

[tool.tox.env_run_base]
dependency_groups = ["dev"]
extras = ["sync"]
commands = [
  ["coverage", "run", "-m", "pytest", {replace = "posargs", default = ["-vvs", "--junit-xml", "test-reports/results.xml"], extend = true}],
  ["coverage", "xml"],
  ["coverage", "html"],
  ["coverage", "report", "-m"]
]

[tool.tox.env_run_base.set_env]
NO_PROXY = "localhost,postgres,elasticsearch"
no_proxy = "localhost,postgres,elasticsearch"

[[tool.uv.index]]
name = "nexus"
url = "https://nexus.osdc.io/repository/pypi-gdc-releases/simple"
